[package]
name = "plant_growth_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.5"
env_logger = "0.11.5"
wgpu = "25.0.2"
pollster = "0.4.0"
thiserror = "2.0.12"
bytemuck = { version = "1.12", features = [ "derive" ] }
once_cell = "1.20.2"
itertools = "0.14.0"
